# Generated by Django 5.0.1 on 2024-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpr',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
