# Generated by Django 5.0.1 on 2024-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpr', '0002_alter_tpr_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpr',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
