# Generated by Django 5.0.3 on 2024-04-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpr', '0003_alter_tpr_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpr',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
